// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0mpXmCD0XxCshkR4Ca7UI2ArH3NcKEvw',
    appId: '1:935587862995:android:fbe0effaa7673603e1f726',
    messagingSenderId: '935587862995',
    projectId: 'cooking-app-38908',
    storageBucket: 'cooking-app-38908.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcydBbpA7leD48COyKbKp-WXf3Fc3wvaM',
    appId: '1:935587862995:ios:d3a624db65d6b608e1f726',
    messagingSenderId: '935587862995',
    projectId: 'cooking-app-38908',
    storageBucket: 'cooking-app-38908.appspot.com',
    iosClientId: '935587862995-pu1r1pcs8garojaihfrkcckgu6o4stlv.apps.googleusercontent.com',
    iosBundleId: 'cooking.app',
  );
}
